name: immutable_model_workspace

packages:
  - immutable_model
  - immutable_model/example
  - immutable_model_gen

# Don't generate intellij files
ide:
  intellij: false

command:
  bootstrap:
    runPubGetInParallel: true

  version:
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: false

scripts:
  format:
    description: Format Dart code.
    run: dart format .

  format:check:
    description: Check formatting of Dart code.
    run: dart format --output none --set-exit-if-changed .

  generate:
    description: Generate Dart code.
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      # orderDependents: true
      depends-on: build_runner

  test:
    run: melos run test:package --no-select
    description: Run all Flutter tests in this project.
  
  test:coverage:
    run: melos run test:package_coverage --no-select
    description: Run all Flutter tests in this project with coverage.
