targets:
  $default:
    builders:
      immutable_models_gen:
        enabled: true
        generate_for:
          exclude:
            - test/gen_test_cases/*

builders:
  immutable_models_gen:
    target: ":immutable_models_gen"
    import: "package:immutable_models_gen/builder.dart"
    builder_factories: ["immutableModelGen"]
    build_extensions: {".dart": [".immutable_models_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]