name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  immutable_models:
    path: ../

dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.6
  
  immutable_models_gen: ^1.0.0
