name: im_model
version: 1.4.0
description: Annotation for immutable model to generate `copyWith` and == (equal) operator.
homepage: https://github.com/llfbandit/immutable_model/tree/master/im_model

topics:
  - immutable
  - immutability
  - copywith
  - equality

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.19.4
