name: immutable_model
version: 1.0.0
description: Annotation for immutable model to generate `copyWith` and == (equal) operator.
homepage: https://github.com/llfbandit/immutable_model/tree/master/immutable_model

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.11.0
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.3

  build_runner: ^2.4.6
  test: ^1.24.4

  immutable_model_gen: ^1.0.0
