targets:
  $default:
    builders:
      immutable_model_gen:
        enabled: true
        generate_for:
          exclude:
            - test/gen_test_cases/*

builders:
  immutable_model_gen:
    target: ":immutable_model_gen"
    import: "package:immutable_model_gen/builder.dart"
    builder_factories: ["copyWith"]
    build_extensions: {".dart": ["immutable_model_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]