name: immutable_model_gen
version: 1.0.0
description: Annotation builder for immutable model to generate of `copyWith` and == (equal) operator..

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ">=5.14.0-dev <7.0.0"
  build: ^2.3.1
  immutable_model: ^1.0.0
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  flutter_lints: ^2.0.3
  build_runner: ^2.4.0
  test: ^1.24.4
  source_gen_test: ^1.0.6
